"""
train_model.py
────────────────────────────────────────────────────────────
Trains the Random Forest feasibility prediction model using
travel_data.csv (generated by data/generate_dataset.py).

Usage:
    cd travel_planner/models
    python train_model.py

Workflow:
    1. Edit destinations.xlsx  (add/remove/edit destinations)
    2. python data/generate_dataset.py   (regenerate dataset)
    3. python models/train_model.py      (retrain model)
    4. Restart Flask                     (model reloads automatically)
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
import pickle
import os

BASE = os.path.dirname(os.path.abspath(__file__))

# ── Load dataset ──────────────────────────────────────────────────────────────
DATA_PATH = os.path.join(BASE, "../data/travel_data.csv")

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"travel_data.csv not found at {DATA_PATH}\n"
        "Run data/generate_dataset.py first."
    )

df = pd.read_csv(DATA_PATH)
print(f"Dataset loaded: {len(df)} records, {df['destination'].nunique()} destinations")

# ── Encode categorical columns ─────────────────────────────────────────────────
cat_cols = ["destination", "destination_type", "from_location",
            "trip_type", "transport", "season"]
encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    df[col + "_enc"] = le.fit_transform(df[col].astype(str))
    encoders[col] = le

# ── Features & target ─────────────────────────────────────────────────────────
FEATURES = [
    "destination_enc",
    "destination_type_enc",
    "from_location_enc",
    "trip_type_enc",
    "transport_enc",
    "season_enc",
    "budget",
    "num_days",
    "total_cost",
]

X = df[FEATURES]
y = df["feasible"]

print(f"Features used: {FEATURES}")
print(f"Class distribution — Feasible: {y.sum()} | Not: {(y==0).sum()}")

# ── Train / Test split ─────────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ── Train Random Forest ────────────────────────────────────────────────────────
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

# ── Evaluate ──────────────────────────────────────────────────────────────────
y_pred = rf.predict(X_test)
acc    = accuracy_score(y_test, y_pred)

print(f"\nModel Accuracy : {acc*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=["Not Feasible", "Feasible"]))

# ── Save model + encoders + feature names ─────────────────────────────────────
MODEL_DIR = os.path.join(BASE)
os.makedirs(MODEL_DIR, exist_ok=True)

with open(os.path.join(MODEL_DIR, "rf_model.pkl"), "wb") as f:
    pickle.dump(rf, f)
with open(os.path.join(MODEL_DIR, "encoders.pkl"), "wb") as f:
    pickle.dump(encoders, f)
with open(os.path.join(MODEL_DIR, "feature_names.pkl"), "wb") as f:
    pickle.dump(FEATURES, f)

print(f"\nModel saved → models/rf_model.pkl")
print(f"Encoders saved → models/encoders.pkl")
print(f"Feature names saved → models/feature_names.pkl")
print("\nRestart Flask to load the new model.")